pipeline {
  agent none
  environment {
    PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
  }
  stages {
    stage('Back-end') {
      agent {
        docker { image 'nginx' }
      }
      steps {
        sh 'nginx --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
